org: lash0000
app: gen-hotel
service: sia-mongo

plugins:
  - serverless-dotenv-plugin
  - serverless-offline

provider:
  name: aws
  versionFunctions: false # to fix large redeployment T_T
  runtime: nodejs20.x
  region: ap-southeast-2
  environment:
    S3_BUCKET_NAME: ${env:S3_BUCKET_NAME}
    S3_BUCKET_URL: ${env:S3_BUCKET_URL}
    FILE_UPLOAD_QUEUE_URL: !Ref FileUploadQueue
    MONGODB_URI: ${env:MONGODB_URI}
    MAIL_USERNAME: ${env:MAIL_USERNAME}
    MAIL_PASSWORD: ${env:MAIL_PASSWORD}
    JWT_REFRESH_SECRET: ${env:JWT_REFRESH_SECRET}
    JWT_ACCESS_SECRET: ${env:JWT_ACCESS_SECRET}
    KEY_ID: ${env:KEY_ID}
    SECRET_ACCESS_ID: ${env:SECRET_ACCESS_ID}
  httpApi:
    cors:
      allowedOrigins:
        - https://hotel-sia-test.vercel.app
        - http://localhost:5000/
      allowedMethods:
        - GET
        - POST
        - PUT
        - DELETE
        - OPTIONS
      allowedHeaders:
        - Content-Type
        - Authorization
      maxAge: 3600

package:
  individually: true
  exclude:
    - test/**
    - .git/**
    - .vscode/**
    - venv/**
    - coverage/**

functions:
  landingArticles:
    handler: app.handler
    timeout: 28
    events:
      - httpApi:
          path: /api/v1/hotel/landing-articles
          method: get
      - httpApi:
          path: /api/v1/hotel/landing-articles/article/{id}
          method: get
      - httpApi:
          path: /api/v1/hotel/landing-articles
          method: post
      - httpApi:
          path: /api/v1/hotel/landing-articles/{id}
          method: put
      - httpApi:
          path: /api/v1/hotel/landing-articles
          method: options
          
  forumAssistance:
    handler: app.handler
    timeout: 28
    events:
      - httpApi:
          path: /api/v1/hotel/forum-assistance
          method: get
      - httpApi:
          path: /api/v1/hotel/forum-assistance/{id}
          method: get
      - httpApi:
          path: /api/v1/hotel/forum-assistance/add-thread
          method: post
      - httpApi:
          path: /api/v1/hotel/forum-assistance/user-comment
          method: post
      - httpApi:
          path: /api/v1/hotel/forum-assistance
          method: options
          
  landingHome:
    handler: app.handler
    timeout: 28
    events:
      - httpApi:
          path: /api/v1/hotel/landing-home
          method: get
      - httpApi:
          path: /api/v1/hotel/landing-home
          method: post
      - httpApi:
          path: /api/v1/hotel/landing-home/{id}
          method: put
      - httpApi:
          path: /api/v1/hotel/landing-home
          method: options

  attendanceLogs:
    handler: app.handler
    timeout: 28
    events:
      - httpApi:
          path: /api/v1/hotel/attendance-log
          method: get
      - httpApi:
          path: /api/v1/hotel/attendance-log
          method: post
      - httpApi:
          path: /api/v1/hotel/attendance-log
          method: options

  guestNotify:
    handler: app.handler
    timeout: 28
    events:
      - httpApi:
          path: /api/v1/hotel/guest-notify
          method: get
      - httpApi:
          path: /api/v1/hotel/guest-notify/{id}
          method: get
      - httpApi:
          path: /api/v1/hotel/guest-notify
          method: post
      - httpApi:
          path: /api/v1/hotel/guest-notify
          method: options
      - httpApi:
          path: /api/v1/hotel/guest-notify/{id}
          method: options

  activityLogs:
    handler: app.handler
    timeout: 28
    events:
      - httpApi:
          path: /api/v1/hotel/hotel-activity-logs
          method: get
      - httpApi:
          path: /api/v1/hotel/hotel-activity-logs/{id}
          method: get
      - httpApi:
          path: /api/v1/hotel/hotel-activity-logs
          method: post
      - httpApi:
          path: /api/v1/hotel/hotel-activity-logs
          method: options
      - httpApi:
          path: /api/v1/hotel/hotel-activity-logs/{id}
          method: options

  bookingReserves:
    handler: app.handler
    timeout: 28
    events:
      - httpApi:
          path: /api/v1/hotel/booking-reservation/archives
          method: get
      - httpApi:
          path: /api/v1/hotel/booking-reservation/archives
          method: post
      - httpApi:
          path: /api/v1/hotel/booking-reservation/archives/{id}
          method: get
      - httpApi:
          path: /api/v1/hotel/booking-reservation/{id}
          method: get
      - httpApi:
          path: /api/v1/hotel/booking-reservation/book/{id}
          method: get
      - httpApi:
          path: /api/v1/hotel/booking-reservation/book/{id}
          method: put
      - httpApi:
          path: /api/v1/hotel/booking-reservation/all
          method: get
      - httpApi:
          path: /api/v1/hotel/booking-reservation
          method: post
      - httpApi:
          path: /api/v1/hotel/booking-reservation/pay-counter
          method: post
      - httpApi:
          path: /api/v1/hotel/booking-reservation/archives
          method: options
      - httpApi:
          path: /api/v1/hotel/booking-reservation/archives/{id}
          method: options
      - httpApi:
          path: /api/v1/hotel/booking-reservation/{id}
          method: options
      - httpApi:
          path: /api/v1/hotel/booking-reservation/book/{id}
          method: options
      - httpApi:
          path: /api/v1/hotel/booking-reservation/all
          method: options
      - httpApi:
          path: /api/v1/hotel/booking-reservation
          method: options
      - httpApi:
          path: /api/v1/hotel/booking-reservation/pay-counter
          method: options

  reservationQueue:
    handler: app.handler
    timeout: 28
    events:
      - httpApi:
          path: /api/v1/hotel/booking-reservation/queues
          method: get
      - httpApi:
          path: /api/v1/hotel/booking-reservation/queues/{id}
          method: get
      - httpApi:
          path: /api/v1/hotel/booking-reservation/queues
          method: post
      - httpApi:
          path: /api/v1/hotel/booking-reservation/queues/{id}
          method: put
      - httpApi:
          path: /api/v1/hotel/booking-reservation/queues/{id}
          method: delete
      - httpApi:
          path: /api/v1/hotel/booking-reservation/queues
          method: options
      - httpApi:
          path: /api/v1/hotel/booking-reservation/queues/{id}
          method: options

  guestAccounts:
    handler: app.handler
    timeout: 28
    events:
      - httpApi:
          path: /api/v1/hotel/guest_accounts/auth/sessions
          method: get
      - httpApi:
          path: /api/v1/hotel/guest_accounts/auth/login
          method: post
      - httpApi:
          path: /api/v1/hotel/guest_accounts
          method: get
      - httpApi:
          path: /api/v1/hotel/guest_accounts
          method: post
      - httpApi:
          path: /api/v1/hotel/guest_accounts/{id}
          method: get
      - httpApi:
          path: /api/v1/hotel/guest_accounts/{id}
          method: put
      - httpApi:
          path: /api/v1/hotel/guest_accounts/paypal-auth
          method: post
      - httpApi:
          path: /api/v1/hotel/guest_accounts/auth/sessions
          method: options
      - httpApi:
          path: /api/v1/hotel/guest_accounts/auth/login
          method: options
      - httpApi:
          path: /api/v1/hotel/guest_accounts
          method: options
      - httpApi:
          path: /api/v1/hotel/guest_accounts/{id}
          method: options
      - httpApi:
          path: /api/v1/hotel/guest_accounts/paypal-auth
          method: options

  uploadQueues:
    handler: app.handler
    timeout: 28
    events:
      - httpApi:
          path: /api/v1/hotel/uploads/queues
          method: get
      - httpApi:
          path: /api/v1/hotel/uploads/queues/{id}
          method: get
      - httpApi:
          path: /api/v1/hotel/uploads/queues
          method: post
      - httpApi:
          path: /api/v1/hotel/uploads/queues/{id}
          method: delete
      - httpApi:
          path: /api/v1/hotel/uploads/queues/user/{id}
          method: delete
      - httpApi:
          path: /api/v1/hotel/uploads/queues
          method: options
      - httpApi:
          path: /api/v1/hotel/uploads/queues/{id}
          method: options
      - httpApi:
          path: /api/v1/hotel/uploads/queues/user/{id}
          method: options

  hotelRooms:
    handler: app.handler
    timeout: 28
    events:
      - httpApi:
          path: /api/v1/hotel/hotel_rooms
          method: get
      - httpApi:
          path: /api/v1/hotel/hotel_rooms/{id}
          method: get
      - httpApi:
          path: /api/v1/hotel/hotel_rooms
          method: post
      - httpApi:
          path: /api/v1/hotel/hotel_rooms/{id}
          method: put
      - httpApi:
          path: /api/v1/hotel/hotel_rooms
          method: options
      - httpApi:
          path: /api/v1/hotel/hotel_rooms/{id}
          method: options

  mediaFiles:
    handler: app.handler
    timeout: 28
    events:
      - httpApi:
          path: /api/v1/hotel/uploads/room_management/media_files
          method: get
      - httpApi:
          path: /api/v1/hotel/uploads/room_management/media_files/{id}
          method: get
      - httpApi:
          path: /api/v1/hotel/uploads/room_management/media_files
          method: post
      - httpApi:
          path: /api/v1/hotel/uploads/room_management/media_files/{id}
          method: delete
      - httpApi:
          path: /api/v1/hotel/uploads/room_management/media_files/user/{id}
          method: delete
      - httpApi:
          path: /api/v1/hotel/uploads/employee_records/media_files
          method: get
      - httpApi:
          path: /api/v1/hotel/uploads/employee_records/media_files/{id}
          method: get
      - httpApi:
          path: /api/v1/hotel/uploads/employee_records/media_files
          method: post
      - httpApi:
          path: /api/v1/hotel/uploads/employee_records/media_files/{id}
          method: delete
      - httpApi:
          path: /api/v1/hotel/uploads/employee_records/media_files/user/{id}
          method: delete
      - httpApi:
          path: /api/v1/hotel/uploads/room_management/media_files
          method: options
      - httpApi:
          path: /api/v1/hotel/uploads/room_management/media_files/{id}
          method: options
      - httpApi:
          path: /api/v1/hotel/uploads/room_management/media_files/user/{id}
          method: options
      - httpApi:
          path: /api/v1/hotel/uploads/employee_records/media_files
          method: options
      - httpApi:
          path: /api/v1/hotel/uploads/employee_records/media_files/{id}
          method: options
      - httpApi:
          path: /api/v1/hotel/uploads/employee_records/media_files/user/{id}
          method: options

  otpRecovery:
    handler: app.handler
    timeout: 28
    events:
      - httpApi:
          path: /api/v1/hotel/otp/forgot_password
          method: get
      - httpApi:
          path: /api/v1/hotel/otp/forgot_password
          method: post
      - httpApi:
          path: /api/v1/hotel/otp/forgot_password
          method: options

  otpRegistration:
    handler: app.handler
    timeout: 28
    events:
      - httpApi:
          path: /api/v1/hotel/otp/registration
          method: get
      - httpApi:
          path: /api/v1/hotel/otp/registration
          method: post
      - httpApi:
          path: /api/v1/hotel/otp/registration
          method: options

  staffAccounts:
    handler: app.handler
    timeout: 28
    events:
      - httpApi:
          path: /
          method: get
      - httpApi:
          path: /api/v1/hotel/staff_accounts
          method: get
      - httpApi:
          path: /api/v1/hotel/staff_accounts/auth/sessions
          method: get
      - httpApi:
          path: /api/v1/hotel/staff_accounts/auth/login
          method: post
      - httpApi:
          path: /api/v1/hotel/staff_accounts
          method: post
      - httpApi:
          path: /api/v1/hotel/staff_accounts/temporary
          method: post
      - httpApi:
          path: /api/v1/hotel/staff_accounts/{id}
          method: get
      - httpApi:
          path: /api/v1/hotel/staff_accounts/{id}
          method: put
      - httpApi:
          path: /
          method: options
      - httpApi:
          path: /api/v1/hotel/staff_accounts
          method: options
      - httpApi:
          path: /api/v1/hotel/staff_accounts/auth/sessions
          method: options
      - httpApi:
          path: /api/v1/hotel/staff_accounts/auth/login
          method: options
      - httpApi:
          path: /api/v1/hotel/staff_accounts/temporary
          method: options
      - httpApi:
          path: /api/v1/hotel/staff_accounts/{id}
          method: options

  auditLogs:
    handler: app.handler
    timeout: 28
    events:
      - httpApi:
          path: /api/v1/hotel/audit_logs
          method: get
      - httpApi:
          path: /api/v1/hotel/audit_logs/{id}
          method: get
      - httpApi:
          path: /api/v1/hotel/audit_logs
          method: post
      - httpApi:
          path: /api/v1/hotel/audit_logs
          method: options
      - httpApi:
          path: /api/v1/hotel/audit_logs/{id}
          method: options

  deleteUnnecessary:
    handler: lateSchedule.handler
    timeout: 28
    events:
      - schedule: cron(*/ *3 * * ? *)

  deleteScheduledFiles:
    handler: queueSchedule.handler
    timeout: 28
    events:
      - schedule: cron(*/ *3 * * ? *)